# Generated by Django 6.0 on 2025-12-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pastebin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin_content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
