# Generated by Django 6.0 on 2025-12-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pastebin_app', '0002_alter_pastebin_content_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastebin_content',
            name='category',
            field=models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('notes', 'Notes'), ('secret', 'Secret'), ('food', 'Food'), ('movies', 'Movies'), ('other', 'Other')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='pastebin_content',
            name='expiry',
            field=models.CharField(choices=[('burn ', 'Burn after read'), ('1_hour', '1 Hour'), ('1_day', '1 Day'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('never', 'Never')], default='never', max_length=20),
        ),
        migrations.AlterField(
            model_name='pastebin_content',
            name='content_paste',
            field=models.TextField(),
        ),
    ]
