# Generated by Django 6.0 on 2025-12-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pastebin_app', '0003_pastebin_content_category_pastebin_content_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastebin_content',
            name='category',
            field=models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('notes', 'Notes'), ('secret', 'Secret'), ('food', 'Food'), ('movies', 'Movies'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='pastebin_content',
            name='expiry',
            field=models.CharField(choices=[('burn', 'Burn after read'), ('1_hour', '1 Hour'), ('1_day', '1 Day'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('6_months', '6 Months'), ('1_year', '1 Year'), ('never', 'Never')], default='1 Hour', max_length=20),
        ),
    ]
